##**CHAPTER 01_PyTorch_BASICS**##  
**DB str dt = 3/03/26**

In [ ]:
#3/3/26 PyTorch DB
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim
#0 dimension tensor

0

In [ ]:
#get tensor back as a python int
scalar.item()

7

In [ ]:
vector = torch.tensor([4,5])
vector
vector.ndim
#1 dimension tensor

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[4,5],
                       [4,2]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor 4/03/26 DB
TENSOR = torch.tensor([[[1,2,3],
                       [3,5,8],
                       [4,8,2]],
                       [[3,4,2],
                        [4,5,2],
                        [4,5,7]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#Random tensors
random_tensor = torch.rand(2,5,5)
random_tensor
random_tensor.mean()


tensor(0.4757)

In [ ]:
#Tensor similar to a image
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.ndim,random_image_size_tensor.shape


(3, torch.Size([244, 244, 3]))

In [ ]:
#Zeros and ones TENSOR
tensor_ones = torch.ones(2,3,4)
tensor_ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
Zero_Tensor = torch.zeros(2,3,5)
Zero_Tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
#torch.arange()
one_to_ten = torch.arange(0,10)

In [ ]:
torch.arange(start=5,end = 55,step=5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###**TENSOR DATA TYPES**
**Note:** PyTorch dtypes are one of the three big errors in PyTorch and DL

1.Tensor not the right Data Type

2.Tensor not the right shape

3.Tensor not on the right device


In [ ]:
#float32 data type
float_32_tensor = torch.tensor( [3.,4.,5.],
                               dtype=None,#What Data type is the tensor(e.g float32,float16)
                               device=None,#What device your Tensor is on
                               requires_grad=False)#Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype
float_16_tensor.device
int_32_tensor = torch.tensor([3,4,5],dtype = torch.int32)
int_32_tensor.device

device(type='cpu')

###CHAPTER 19###
***manipulating tensors***

Tensor Operations include

* Addition

* Subtraction

* Multiplication(Element wise)

* Division

* Matrix-Multiplication


In [ ]:
#Tensor operations(Modifying tensors)
#Adding
tensor = torch.tensor([1,2,3])
tensor + 10 #Add 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
mult_tensor = tensor * 10

In [ ]:
#Dividing tensors by 2
mult_tensor/2

tensor([ 5., 10., 15.])

In [ ]:
#subtract ten
mult_tensor - 10

tensor([ 0, 10, 20])

**In-Built functions of PyTorch**

In [ ]:
#In-Built functions of PyTorch Multiplication
torch.mul(tensor,2)

tensor([2, 4, 6])

In [ ]:
#Addition
torch.add(tensor,5)

tensor([6, 7, 8])

In [ ]:
#Subtraction
torch.sub(tensor,1)

tensor([0, 1, 2])

In [ ]:
#Division
torch.div(mult_tensor,2)

tensor([ 5., 10., 15.])

###MATRIX Multiplication
two main ways of multiplying matrix in Deep Learning and machine learning

1.Element based multiplication

2.Matrix based(Dot-product)


In [ ]:
#Element-Wise multiplication
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#MATRIX MULTIPLICATION(DOT PRODUCT)Day 3 5/03/26
torch.matmul(mult_tensor,tensor)


tensor(140)

In [ ]:
torch.matmul(MATRIX,MATRIX)

tensor([[36, 30],
        [24, 24]])

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 865 µs, sys: 2 µs, total: 867 µs
Wall time: 2.9 ms


tensor(14)

##Shape Errors are common

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
#torch.mm is short for torch.matmul()
torch.matmul(tensor_A,tensor_B.T)#transposed tensor_B

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

To fix our tensor shape issues,we can manipulate shape of one of our tensors using a **transpose**

**transponse** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T #.T switches the dimension allowing to matmul

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

##Finding min,max,mean,sum etc.(Tensor Aggregation)


In [ ]:
x = torch.arange(0,100,10)
x
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))#the torch.mean() requires a tensor of float32 dtype dont forget to convert

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
man = torch.tensor([43,61,52,74,72,24,5,32,34])
man

tensor([43, 61, 52, 74, 72, 24,  5, 32, 34])

In [ ]:
man.argmin()#gives the position of the smallest tensor with argmin()

tensor(6)

In [ ]:
man.argmax()#gives the position of the largest tensor with argmax()

tensor(3)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to desired shape

* View - Returns view of an input tensor of certain shape but keep same memory as the original tensor

* Stacking - combines multiple tensors on top of each other (vstack) or side-by-side (hstack)

* Squeez - removes all the `1` dimension from the tensor

* unsqueez - ass a `1` dimension to a target tensor

* permute - return the view of the input with dimensions permuted(swapped) in certain way



In [ ]:
#tensor
x = torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
reshaped_tensor = x.reshape(2,5)
reshaped_tensor,reshaped_tensor.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
#change the view
z = x.view(2,5)
z, z.size()

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
#changing in z will change in `x` as it shares memeory with the original one

In [ ]:
#stacking tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
#torch.squeez removes all single dimensions form a target tensor
test_tensor = torch.tensor([[1,4,1,3,1,4,1,5]])
test_tensor.shape
test_tensor.squeeze().shape

torch.Size([8])

In [ ]:
tensor_x = torch.tensor([[[1,2,4,6,2,5]]])
tensor_x.shape

torch.Size([1, 1, 6])

In [ ]:
tensor_x.squeeze().shape
squeezed_tensor_x = tensor_x.squeeze()

In [ ]:
#torch.permute -rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[Height,width,color_channels]
#permute the origibal trensor to rearrange the axes or dims of the order
x_permuted = x_original.permute(2,0,1) #shifts axes 0->1,1->2,2->0
print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")#[Color_chanel,height,width]

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


##indexing(selecting Data from a TENSOR)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#indexing from outermost
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# from the second
x[0,0] #or x[0] [0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]
# or x[0][0][0]

tensor(1)

In [ ]:
#we can also use ":" to select "all" of a target dim
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[0,1,:]

tensor([4, 5, 6])

##PyTorch tensors and NumPy
* Data in NumPy want in Torch `torch.from_numpy(ndarray)`
* PyTorch tensor in numPy `torch.tensor.numpy()`

In [ ]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)#in NumPy ist der standarddatentype fur arrays float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
array = array + 1
array,tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
#tensor to Numpy Array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility(Trying to take random out of random)

neural N working

`Start with randon no.->tensor operations -> update random numbers to try and make them better representation of data ->again-->again->again...`

To reduce the randomness in pyTorch and NNs there is a concept of **Random Seed**.

what the random does is 'flavour' the randomness


In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
random_tensor_A, random_tensor_B

(tensor([[0.5744, 0.5805, 0.8764, 0.8702],
         [0.0454, 0.0612, 0.5644, 0.4752],
         [0.0603, 0.6771, 0.2604, 0.6517]]),
 tensor([[0.0229, 0.6215, 0.6890, 0.9303],
         [0.5354, 0.8095, 0.2834, 0.5423],
         [0.3729, 0.5475, 0.0265, 0.8162]]))

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
#torch.manual_seed
print(random_tensor_C, random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##1.Running tensors and pytorch objects on GPU(and making faster computation)


In [ ]:
!nvidia-smi


Mon Mar  9 09:56:38 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

##2.check for GPU access with PyTorch

In [2]:
#check for GPU access
import torch
torch.cuda.is_available()

True

In [4]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "CPU"
device

'cuda'

In [ ]:
#count the number of devices
torch.cuda.device_count()

1

3.##Putting tensors and models on GPU

for faster computation


In [11]:
#creates a tensor(on CPU by def)
tensor = torch.tensor([1,2,3,4,4])
print(tensor, tensor.device)

tensor([1, 2, 3, 4, 4]) cpu


In [13]:
#use tensor.to(device) to shift tensor to GPU(cuda)(if available)
tensor_on_gpu = tensor.to(device) #here device = cuda(from the device agnostic code)
tensor_on_gpu

tensor([1, 2, 3, 4, 4], device='cuda:0')

##4.Putting Tensors back to CPU

In [30]:
#if tensor is on GPU we cant convert it to NumPy nparray
import numpy as np
tensor_back_cpu.numpy()

array([1, 2, 3, 4, 4])

In [33]:
#to fix GPU tensor with NumPy issue we can transfer it on CPU
tensor_back_cpu = tensor_on_gpu.cpu()
tensor_back_cpu

tensor([1, 2, 3, 4, 4])