##**CHAPTER 01_PyTorch_BASICS**##  
**DB str dt = 3/03/26**

In [26]:
#3/3/26 PyTorch DB
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
#Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim
#0 dimension tensor

0

In [ ]:
#get tensor back as a python int
scalar.item()

7

In [ ]:
vector = torch.tensor([4,5])
vector
vector.ndim
#1 dimension tensor

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[4,5],
                       [4,2]])
MATRIX
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor 4/03/26 DB
TENSOR = torch.tensor([[[1,2,3],
                       [3,5,8],
                       [4,8,2]],
                       [[3,4,2],
                        [4,5,2],
                        [4,5,7]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
#Random tensors
random_tensor = torch.rand(2,5,5)
random_tensor
random_tensor.mean()


tensor(0.5118)

In [ ]:
#Tensor similar to a image
random_image_size_tensor = torch.rand(size=(244,244,3))
random_image_size_tensor.ndim,random_image_size_tensor.shape


(3, torch.Size([244, 244, 3]))

In [ ]:
#Zeros and ones TENSOR
tensor_ones = torch.ones(2,3,4)
tensor_ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
Zero_Tensor = torch.zeros(2,3,5)
Zero_Tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
#torch.arange()
one_to_ten = torch.arange(0,10)

In [ ]:
torch.arange(start=5,end = 55,step=5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###**TENSOR DATA TYPES**
**Note:** PyTorch dtypes are one of the three big errors in PyTorch and DL

1.Tensor not the right Data Type

2.Tensor not the right shape

3.Tensor not on the right device


In [ ]:
#float32 data type
float_32_tensor = torch.tensor( [3.,4.,5.],
                               dtype=None,#What Data type is the tensor(e.g float32,float16)
                               device=None,#What device your Tensor is on
                               requires_grad=False)#Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 4., 5.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype
float_16_tensor.device
int_32_tensor = torch.tensor([3,4,5],dtype = torch.int32)
int_32_tensor.device

device(type='cpu')

###CHAPTER 19###
***manipulating tensors***

Tensor Operations include

* Addition

* Subtraction

* Multiplication(Element wise)

* Division

* Matrix-Multiplication


In [28]:
#Tensor operations(Modifying tensors)
#Adding
tensor = torch.tensor([1,2,3])
tensor + 10 #Add 10

tensor([11, 12, 13])

In [31]:
# multiply tensor by 10
mult_tensor = tensor * 10

In [32]:
#Dividing tensors by 2
mult_tensor/2

tensor([ 5., 10., 15.])

In [33]:
#subtract ten
mult_tensor - 10

tensor([ 0, 10, 20])

**In-Built functions of PyTorch**

In [38]:
#In-Built functions of PyTorch Multiplication
torch.mul(tensor,2)

tensor([2, 4, 6])

In [37]:
#Addition
torch.add(tensor,5)

tensor([6, 7, 8])

In [40]:
#Subtraction
torch.sub(tensor,1)

tensor([0, 1, 2])

In [41]:
#Division
torch.div(mult_tensor,2)

tensor([ 5., 10., 15.])